config/routes.rb
PubApp::Application.routes.draw do

  root :to => 'blogs#index'

  
  resources :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :title, :details, :author
  
  validates :title, :presence => true, :length => {:maximum => 100}
  validates :details, :presence => true, :length => {:maximum => 500}
  validates :author, :presence => true, :length => {:maximum => 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
  respond_to :html
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.haml
= semantic_form_for(@blog, :url => {:action => "update", :controller => "blogs"}, :html => {:class => 'form-horizontal'}) do |f|
  = f.inputs :name => "New Heirarchy Info" do
    .control-group
      = f.input :title
    .control-group
      = f.input :details
    .control-group
      = f.input :author
    = f.actions do
      .span3
        = f.action :submit, :label => 'Save', :as => :button, :button_html => {:class =>'btn btn-primary'}
      .span2
        = f.action :cancel, :as => :link, :url => root_path, :label => 'Cancel', :button_html => {:class =>'btn'}

app/views/blogs/index.html.haml
%h1 List of blogs
%table.table.table-bordered
  %thead
    %tr
      %th Title
      %th Author
      %th Created At
      %th Actions
  %tbody
    - if @blogs.blank?
      %tr.warning.slanting-center
        %td{:colspan => 4} No Records to show
    - else
      - @blogs.each do |x|
        %tr
          %td=x.title
          %td=x.author
          %td=x.created_at
          %td
            = link_to "View", blog_path(x)
            = link_to "Edit", edit_blog_path(x)

= link_to 'Create new blog', new_blog_path, :class => 'btn'

app/views/blogs/new.html.haml
= semantic_form_for(@blog, :url => {:action => "create", :controller => "blogs"}, :html => {:class => 'form-horizontal'}) do |f|
  = f.inputs :name => "New Heirarchy Info" do
    .control-group
      = f.input :title
    .control-group
      = f.input :details
    .control-group
      = f.input :author
    = f.actions do
      .span3
        = f.action :submit, :label => 'Save', :as => :button, :button_html => {:class =>'btn btn-primary'}
      .span2
        = f.action :cancel, :as => :link, :url => root_path, :label => 'Cancel', :button_html => {:class =>'btn'}

app/views/blogs/show.html.haml
%h1=@blog.title
%table.table.table-bordered
  %tbody
    %tr
      %th Details
      %td=@blog.details
    %tr
      %th Author
      %td=@blog.author

= link_to 'Back', blogs_path, :class => 'btn'

app/views/layouts/application.html.haml
!!! 5
%head
  = render "layouts/partials/stylesheet"

%body{ :id => "pub_app-#{controller.controller_name}", :class => "#{controller.controller_name}" }
  = render "layouts/partials/navbar"
  .div45
  .container
    = yield
  = render "layouts/partials/javascript"

app/views/layouts/partials/_javascript.html.haml
= javascript_include_tag :application
= javascript_include_tag "less.js"
= javascript_include_tag "bootstrap/bootstrap-affix.js"
= javascript_include_tag "bootstrap/bootstrap-alert.js"
= javascript_include_tag "bootstrap/bootstrap-button.js"
= javascript_include_tag "bootstrap/bootstrap-carousel.js"
= javascript_include_tag "bootstrap/bootstrap-collapse.js"
= javascript_include_tag "bootstrap/bootstrap-dropdown.js"
= javascript_include_tag "bootstrap/bootstrap-modal.js"
= javascript_include_tag "bootstrap/bootstrap-popover.js"
= javascript_include_tag "bootstrap/bootstrap-scrollspy.js"
= javascript_include_tag "bootstrap/bootstrap-tab.js"
= javascript_include_tag "bootstrap/bootstrap-tooltip.js"
= javascript_include_tag "bootstrap/bootstrap-transition.js"
= javascript_include_tag "bootstrap/bootstrap-typeahead.js"

app/views/layouts/partials/_navbar.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Pub-App", root_path, :class => "brand"

app/views/layouts/partials/_stylesheet.html.haml
= stylesheet_link_tag "bootstrap.less"
= yield :stylesheets